# Generated by Django 4.1 on 2022-08-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("company_name", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=250)),
                (
                    "balance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=250),
                ),
                ("oval_reference", models.CharField(max_length=20)),
                ("yield_offering_id", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeeProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("transaction_pin", models.IntegerField(blank=True, null=True)),
                ("oval_reference", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=250)),
                ("department", models.CharField(max_length=250)),
                ("salary", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
