# Generated by Django 4.1 on 2022-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="oval_customer_id",
            field=models.CharField(default="1234", max_length=250),
        ),
        migrations.AddField(
            model_name="employeeeprofile",
            name="oval_customer_id",
            field=models.CharField(default="1234", max_length=250),
        ),
    ]
